update go binding code and example app
Here is a list on what I cleaned up (not a complete list):
  - Simplify the usability and utilize the full JSON-c configuration.
  - Remove some files that are combined into others and rework a few areas to
    make it easier to understand.
  - Rework RxBurst/TxBurst/… to take a lportID instead of passing a method pointer.
  - Cleaned up a number of allocations around LPort as this data is static after startup.
  - Remove all of the underscore variables and convert them to Go variable names.
  - Add the start of documentation to all of the files. Needs more work.
  - Added a few more helper routines to parse a slice to packets or objects.
  - Update the example/fwd application to utilize the JSON-c instead of JSON
  - Remove the -port option and use the JSON-c thread section to identify the lports
    attached to a given thread
  - Add support for using the JSON Threads section for starting threads an assigning
    lports to those threads.
  - Use the tview Go library to display the stats in a easier to read format.
  - Update the test routines to poll more than just one lport.
  - Updated the cne/run_test code and script to test more functions.
  - Updated the example/run_fwd script remove the -port option with other cleanups.
  - Fix the tx only packet format as it was missing part of the packet data
  - More minor changes for refactoring and cleanup.

Signed-off-by: Keith Wiles <keith.wiles@intel.com>

diff --git a/lang/go/bindings/examples/fwd/run_fwd b/lang/go/bindings/examples/fwd/run_fwd
--- a/lang/go/bindings/examples/fwd/run_fwd
+++ b/lang/go/bindings/examples/fwd/run_fwd
@@ -1,32 +1,25 @@
 #!/bin/bash
 
-while getopts c:t:p: option
-do 
-    case "${option}"
-        in
-        c)config=${OPTARG};;
-        t)test=${OPTARG};;
-        p)lports=${OPTARG};;
-        \? ) echo "Usage: run_fwd -c <path to config file> -t <test type> -p <comma-separated lport string>";;
-    esac
-done
-
-cdir=`pwd`
+cdir=$(pwd)
 PROJECT_PATH="${cdir}/../../../../.."
 
-IFS=','
-lportsstr=""
-for lport in $lports; 
-do   
-    lportsstr+="-p `echo $lport | xargs` "; 
-done
+cmdstring="sudo -E LD_LIBRARY_PATH=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu \
+    LD_PRELOAD=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu/libpmd_af_xdp.so ./fwd $*"
+
+go mod tidy
+rc=$?
+if [[ $rc -ne 0 ]]; then
+    echo "Go tidy failed"
+    exit $rc
+fi
 
 go build
+rc=$?
+if [[ $rc -ne 0 ]]; then
+    echo "Go build failed"
+    exit $rc
+fi
 
-cmdstring="sudo -E LD_LIBRARY_PATH=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu \
-LD_PRELOAD=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu/libpmd_af_xdp.so \
-./fwd -c $config -t $test $lportsstr"
-
-eval $cmdstring
+$cmdstring
 
 stty sane
