update go binding code and example app
Here is a list on what I cleaned up (not a complete list):
  - Simplify the usability and utilize the full JSON-c configuration.
  - Remove some files that are combined into others and rework a few areas to
    make it easier to understand.
  - Rework RxBurst/TxBurst/… to take a lportID instead of passing a method pointer.
  - Cleaned up a number of allocations around LPort as this data is static after startup.
  - Remove all of the underscore variables and convert them to Go variable names.
  - Add the start of documentation to all of the files. Needs more work.
  - Added a few more helper routines to parse a slice to packets or objects.
  - Update the example/fwd application to utilize the JSON-c instead of JSON
  - Remove the -port option and use the JSON-c thread section to identify the lports
    attached to a given thread
  - Add support for using the JSON Threads section for starting threads an assigning
    lports to those threads.
  - Use the tview Go library to display the stats in a easier to read format.
  - Update the test routines to poll more than just one lport.
  - Updated the cne/run_test code and script to test more functions.
  - Updated the example/run_fwd script remove the -port option with other cleanups.
  - Fix the tx only packet format as it was missing part of the packet data
  - More minor changes for refactoring and cleanup.

Signed-off-by: Keith Wiles <keith.wiles@intel.com>

diff --git a/lang/go/bindings/cne/run_test b/lang/go/bindings/cne/run_test
--- a/lang/go/bindings/cne/run_test
+++ b/lang/go/bindings/cne/run_test
@@ -1,21 +1,31 @@
 #!/bin/bash
 
-project_path="${PROJECT_PATH:-/root/git/networking.dataplane.cndp.cndp}"
+cdir=$(pwd)
+PROJECT_PATH="${cdir}/../../../.."
 
-go build
+precmd="sudo -E LD_LIBRARY_PATH=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu LD_PRELOAD=$PROJECT_PATH/usr/local/lib/x86_64-linux-gnu/libpmd_af_xdp.so"
+cmdstring="$precmd ./cne.test -test.v -config ../examples/fwd/fwd.jsonc"
 
-#go test
-sudo -E LD_LIBRARY_PATH=$project_path/usr/local/lib/x86_64-linux-gnu LD_PRELOAD=$project_path/usr/local/lib/x86_64-linux-gnu/libpmd_af_xdp.so go test -port "enp25s0f0:0" -config "/root/git/networking.dataplane.cndp.cndp/lang/go/cndp.org/examples/fwd/fwd.json" -v
+function go_tidy() {
+    go mod tidy
+    rc=$?
+    if [[ $rc -ne 0 ]]; then
+        echo "Go tidy failed"
+        exit $rc
+    fi
+}
 
-#go test cover
-#sudo -E LD_LIBRARY_PATH=$project_path/usr/local/lib/x86_64-linux-gnu LD_PRELOAD=$project_path/usr/local/lib/x86_64-linux-gnu/libpmd_af_xdp.so go test -v -cover
+function go_test() {
+    go test -c
+    rc=$?
+    if [[ $rc -ne 0 ]]; then
+        echo "Go test failed"
+        exit $rc
+    fi
+}
 
-#go bench
-sudo -E LD_LIBRARY_PATH=$project_path/usr/local/lib/x86_64-linux-gnu LD_PRELOAD=$project_path/usr/local/lib/x86_64-linux-gnu/libpmd_af_xdp.so go test -port "enp25s0f0:0" -config "/root/git/networking.dataplane.cndp.cndp/lang/go/cndp.org/examples/fwd/fwd.json"  -bench=.
+rm -f cne.test
+(go_tidy && go_test && $cmdstring)
 
-#go bench profiles
-#sudo -E LD_LIBRARY_PATH=$project_path/usr/local/lib/x86_64-linux-gnu LD_PRELOAD=$project_path/usr/local/lib/x86_64-linux-gnu/libpmd_af_xdp.so go test -cpuprofile cpu.prof -memprofile mem.prof -bench=.
-#go tool pprof -pdf cpu.prof > cpu.pdf
-#go tool pprof -pdf mem.prof > mem.pdf
-
+rm -f cne.test
 stty sane
